# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://lixiang.dev"

# Basic metadata configuration for your blog.
title = "Li Xiang's Brain Dump"
languageCode = "en-US"

# Enable emoji
enableEmoji = true

# The built-in RSS template will render the following values, if present, from your site
# configuration:
copyright = 'Copyright © 2024 Li Xiang.'

assetDir = "static"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # Sentence you wanna show in the footer, markdown supported.
  footer = 'Dear wind, please take [me](mailto:shu@lixiang.dev "Wanna mail to cool me? ٩(^ᗜ^ )و") fly'

  # The "description" of your website. This is used in the meta data of your generated html.
  description = "I am cool B)"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static/favicon"-folder.
  # Default is light.
  favicon = "/favicon/light/favicon.ico"
  # Dark version of your "favicon".
  favicon_dark = "/favicon/dark/favicon.ico"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/bird.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Li Xiang's Brain Dump"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  hideMadeWithLine = false
  hideCopyright = false

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "02 Jan, 2006"

  # The built-in RSS template will render the following values, if present, from your site
  # configuration:
  [params.author]
    email = 'shu@lixiang.dev'
    name = 'Li Xiang' # This will show in the copyright.
# =================================================================================
# By default, when you build your site, Hugo generates RSS feeds for home, section,
# taxonomy, and term pages. Control feed generation in your site configuration. For
# example, to generate feeds for homeand section pages, but not for taxonomy and term
# pages:
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  term = ['html']

# To disable feed generation or sitemap for all page kinds:
# disableKinds = ['rss', 'sitemap']
# =================================================================================
[sitemap]
  # How frequently a page is likely to change. Valid values are always, hourly, daily, weekly, monthly,
  # yearly, and never. With the default value of "" Hugo will omit this field from the sitemap.
  changeFreq = 'daily'
  # Whether to disable page inclusion. Default is false. Set to true in front matter to exclude the page.
  disable = false
  # The name of the generated file. Default is sitemap.xml.
  filename = 'sitemap.xml'
  # The priority of a page relative to any other page on the site. Valid values range from 0.0 to 1.0. With
  # the default value of -1 Hugo will omit this field from the sitemap.
  priority = -1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = false
