elevant part of my netlify.toml:

[context.production.environment]
	HUGO_VERSION = "0.136.0"
	HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.136.0"

[build]
	publish = "public"
	command = "hugo --minify --buildFuture"
